version: 2
jobs:
  build:
    environment:
      - USER: circleci
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-test-deps-{{ arch }}-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}
            - v1-test-deps-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Setup Packer build environment
          command: |
            python -m virtualenv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements.txt
            curl https://releases.hashicorp.com/packer/1.1.1/packer_1.1.1_linux_amd64.zip > /tmp/packer.zip
            unzip /tmp/packer.zip
            sudo mv packer /usr/local/bin
      - run:
          name: Validate Packer template
          command: |
            . ~/venv/bin/activate
            packer validate template.json
      - run:
          name: Build Packer template
          command: |
            . ~/venv/bin/activate
            packer build template.json
      - run:
          name: Setup test environment dependencies
          command: |
            . ~/venv/bin/activate
            pip install -r tests/requirements.txt
      - save_cache:
          key: v1-test-deps-{{ arch }}-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}
          paths:
            - ~/venv
      - run:
          name: Verify built image
          command: |
            . ~/venv/bin/activate
            mkdir -p /tmp/pytest-results
            py.test -v tests --junit-xml=/tmp/pytest-results/output.xml
      - store_test_results:
          path: /tmp/pytest-results
      - store_artifacts:
          path: /tmp/pytest-results
